spring:
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    port: 6379
    host: 222.178.212.29
    password: smart99--
    database: 8
    jedis:
      pool:
        min-idle: 10
        max-idle: 20
        max-wait: -1ms
        max-active: 200
    # 是否分布式
    isSharded: false
    # 最大连接数
    maxTotal: 5000
    # 最大空闲连接数
    maxIdle: 1000
    # 建立连接时，最大等待时间
    maxWaitMillis: 60000
    # 建立连接时，是否进行有效性检查
    testOnBorrow: true
jsy:
  upload:
    type: oss
  oss:
    aliyun:
      enable: true
      end-point: ada
      access-key-id: 2gaga
      access-key-secret: sgsagsd
      bucket-name: test
  shiro:
    redis: false
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: XW-EC7D505B-3435-4728-9B04-84513C2BF0EE
    # token有效时长，7天，单位秒
    expire: 604800
    header: token